data:
  path_to_logs : "logs\\scalars\\"
  path_to_checkpoints : "checkPoints\\"
  path_to_model : "saved_models\\"

pre_processing:
  image_size : 224
  train_path: "Data/train"
  val_path: "Data/val"
  classes: None
  batch_size_train: 100
  batch_size_test: 24
  class_mode: "categorical"
  horizontal_flip: True
  rotation_range: 0.02
  zca_whitening: True
  width_shift_range: 0.05
  height_shift_range: 0.05
  zoom_range: [0.8,1.0]
  save_to_dir: None
  interpolation: "nearest"

compile:
  loss : 'categorical_crossentropy'
  metrics : ["accuracy"]

optimizer:
  lr : 0.0001
  beta_1 : 0.9
  beta_2 : 0.999
  epsilon : 0.0000001
  amsgrad : False

fit:
  batch_size : 1
  epochs : 5
  verbose : 'auto'
  validation_split : 0.0
  shuffle : True 
  class_weight :
  sample_weight : 
  initial_epoch : 0
  steps_per_epoch :
  validation_steps : 
  validation_batch_size : 
  validation_freq : 1
  max_queue_size : 10
  workers : 1
  use_multiprocessing: 1

predict:
  batch_size : 1
  verbose : 'auto'
  steps : 
  max_queue_size : 10
  workers : 1
  use_multiprocessing : False
