data:
  path_to_logs : "logs\\scalars\\"
  path_to_checkpoints : "checkPoints\\"
  path_to_model : "saved_models\\"

pre_processing:
  

compile:
  loss : 'categorical_crossentropy'
  metrics : ["accuracy"]

optimizer:
  lr : 0.0001
  beta_1 : 0.9
  beta_2 : 0.999
  epsilon : 0.0000001
  amsgrad : False

fit:
  batch_size : 1
  epochs : 5
  verbose : 'auto'
  validation_split : 0.0
  shuffle : True 
  class_weight :
  sample_weight : 
  initial_epoch : 0
  steps_per_epoch :
  validation_steps : 
  validation_batch_size : 
  validation_freq : 1
  max_queue_size : 10
  workers : 1
  use_multiprocessing: 1

predict:
  batch_size : 1
  verbose : 'auto'
  steps : 
  max_queue_size : 10
  workers : 1
  use_multiprocessing : False
